version: "{build}"
clone_depth: 1
image: Ubuntu

build_script:
- sh: sudo apt-get -y update
- sh: sudo apt-get -y install libsdl2-dev libopenal-dev libogg-dev libvorbis-dev libtheora-dev
- sh: git submodule update --init --recursive
- sh: cd source
- sh: cmake .
- sh: make -j$(nproc --all)
